spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://client-microservice
          predicates:
            - Path=/clients/**
        - id: card
          uri: lb://card-microservice
          predicates:
            - Path=/cards/**
        - id: credit-evaluator
          uri: lb://credit-evaluator-ms
          predicates:
            - Path=/credit-evaluator/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/credit-evaluator-microservices

#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:eureka-password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

server:
  port: 8080