spring:
  application:
    name: credit-evaluator-ms
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:eureka-password@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring-batch.application.instance_id:${random.value}}

mq:
  queues:
    card-issuance: card-issuance

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log